services:
  teleop:
    build: .
    image: isaac-teleop:6.0.1
    container_name: teleop
    environment:
      - OMNI_KIT_ACCEPT_EULA=YES
      - ACCEPT_EULA=Y
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ${HOME}/isaac-teleop-share:/share
      - ${HOME}/workspace:/root/workspace
      - ${HOME}/workspace/Isaac-GR00T-N1.7/GR00T-WholeBodyControl:/workspace/wbc
      - ${HOME}/workspace/artvip_scenes:/root/isaac-sim/artvip_scenes
    network_mode: host
    working_dir: /opt/IsaacLab
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
